// pack_locations.mjs — repack the town so each building TYPE forms a tight
// apartment COMPLEX: members occupy CONTIGUOUS cells (no empty gap cells between
// rooms), complexes are laid out in a strip with a small grass gap between them,
// and every location gets a `complex` id the renderer groups by. Parks & squares
// are placed as standalone green plots below the strip. Rewrites js/data/seedLocations.js.
//
// Run: node tools/pack_locations.mjs
import { SEED_LOCATIONS } from "../js/data/seedLocations.js";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "js", "data", "seedLocations.js");

const isOutdoor = (l) => l.type === "park" || l.type === "square";
const buildings = SEED_LOCATIONS.filter((l) => !isOutdoor(l));
const outdoor = SEED_LOCATIONS.filter(isOutdoor);

// group buildings by type, splitting large type-groups into complexes of <= MAX
const MAX = 8;
const byType = new Map();
for (const l of buildings) { if (!byType.has(l.type)) byType.set(l.type, []); byType.get(l.type).push(l); }
const complexes = [];
let cid = 0;
for (const [type, locs] of byType) {
  for (let i = 0; i < locs.length; i += MAX) {
    const members = locs.slice(i, i + MAX);
    const n = members.length;
    const cols = Math.max(2, Math.min(5, Math.round(Math.sqrt(n * 1.5)))); // wider than tall
    const rows = Math.ceil(n / cols);
    complexes.push({ id: "cx" + cid++, type, members, cols, rows });
  }
}
// biggest complexes first so the strip packs tightly
complexes.sort((a, b) => b.rows - a.rows || b.cols - a.cols);

// lay complexes left→right in a strip, wrapping; 2-cell grass gap between them
const STRIP_W = 44, GAP = 2;
let ox = 1, oy = 1, rowH = 0;
for (const cx of complexes) {
  if (ox + cx.cols > STRIP_W) { ox = 1; oy += rowH + GAP; rowH = 0; }
  cx.members.forEach((l, k) => {
    l.x = ox + (k % cx.cols);
    l.y = oy + Math.floor(k / cx.cols); // row-major: members fill contiguous cells
    l.complex = cx.id;
  });
  ox += cx.cols + GAP;
  rowH = Math.max(rowH, cx.rows);
}

// outdoor plots (parks/squares) spread below the building strip
let px = 2, py = oy + rowH + 3;
for (const l of outdoor) {
  l.x = px; l.y = py; l.complex = "out_" + l.id;
  px += 4; if (px > STRIP_W) { px = 2; py += 4; }
}

// sanity: unique coords
const seen = new Set();
for (const l of SEED_LOCATIONS) { const k = l.x + "," + l.y; if (seen.has(k)) throw new Error("dup coord " + k + " at " + l.id); seen.add(k); }

const header =
`// seedLocations.js — town packed into apartment COMPLEXES (contiguous rooms, no
// gaps). Generated by tools/pack_locations.mjs. Each location carries a 'complex'
// id; townArt groups by it and draws one shared shell per complex. Re-run the tool
// to re-pack. IDs/types/tags are unchanged — only x/y and 'complex' are assigned.

`;
writeFileSync(OUT, header + "export const SEED_LOCATIONS = " + JSON.stringify(SEED_LOCATIONS, null, 2) + ";\n");
console.log(`packed ${buildings.length} rooms into ${complexes.length} complexes + ${outdoor.length} outdoor plots; grid ${Math.max(...SEED_LOCATIONS.map((l) => l.x)) + 1}x${Math.max(...SEED_LOCATIONS.map((l) => l.y)) + 1}`);
